### ISSUE TITLE
dg.sheet.init creates multiple addEventListener("keydown"

### ISSUE THREAD

**Issue by stepandersen** [SwedbankPay/design.swedbankpay.com#284]
Sheet is adding a new eventListener for keydown (to listen for esc key) every time a `dg.sheet.init` is called.
https://github.com/SwedbankPay/design.swedbankpay.com/blob/2d498be235b9534fd596b04b810ec46ec8b71338/src/scripts/main/sheet/index.js#L118

If I do this:
```
dg.sheet.init("my-edit-sheet");
dg.sheet.init("my-create-sheet");
```
Two eventListeners for keydown will be created, both looping through the _sheets array to close the open sheets.
```
...
 _sheets.forEach(sheet => sheet.isOpen ? sheet.close() : null);
...
```
Suggested solution:
Register that `document.addEventListener("keydown", e => {` is set, and prevent it from registering it again if it has already been set. As long as the sheet are added to _sheets array, the sheet will be closed by that first eventListener.

**Comment by stepandersen** [comment]
As a side note, we might also want to prevent _sheets from registering the same sheet twice.
```
dg.sheet.init("my-edit-sheet");
dg.sheet.init("my-edit-sheet");
```

Will add two sheets to _sheets, and loop through both of them on e.g. `_sheets.forEach(sheet => sheet.isOpen ? sheet.close() : null);`.

I added this as a comment since users of the design guide shouldn't actually call `init` on the same sheet twice. But it might be right to prevent it if they do.

**Comment by pthoang** [comment]
Not sure if this sufficiently resolves your issue, but according to MDN, duplicate eventListeners should still be called once, as long as they are considered identical to eachother (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Multiple_identical_event_listeners)
Some changes to the code will be made to ensure that the eventListeners are considered identical
