### ISSUE TITLE
Sheet locks scroll permanently if not closed

### ISSUE THREAD

**Issue by stepandersen** [SwedbankPay/design.swedbankpay.com#291]
**To Reproduce**
1. Go to https://design.swedbankpay.com/v/4.5.0/docs/getting-started/contributing (e.g.)
2. Scroll down and back up (scroll works)
3. Select Components > Sheet in sidebar
4. Click Open sheet
5. Click back in browser
6. Contributing page (or any other page) is now unscrollable

**Comment by stepandersen** [comment]
I believe there is another unwanted issue here too:
If you do the steps to reproduce and then open a sheet: the body does not get the `.has-vscroll` class.
Now if you close the sheet and open it again: the body get `.has-vscroll` (in addition to `sheet-open`)
I suppose this happens because opening a sheet toggles class `has-vscroll`, it should rather set it explicitly and remove it explicitly on close

**Comment by stepandersen** [comment]
Some more insight:
`body.sheet-open {
    overflow: hidden;
}`
`overflow: hidden` actually prevents scroll event to trigger, I thought maybe ...
`window.addEventListener('scroll', function(){
console.log("scroll");
}, false);`
...could test if a sheet is actually open, but it doesn't work. The event isn't triggered because of `overflow: hidden` on body.

The reason for this logic is to prevent scrolling of background body when a sheet is open, and that it should do. Doing that without overflow rule sounds hacky.

An option would be to try to remove `body.has-vscroll` and `body.sheet-open` on back-/forward button events, but I didnt like what you have to do to get that working in the examples I have found

**Comment by VikingTristan** [comment]
Could a `hashchange` event listener suffice?

**Comment by VikingTristan** [comment]
I can probably look into this throughout the day unless you have time, @pthoang ?

**Comment by pthoang** [comment]
@VikingTristan would be nice if you have time. If not, then I will look into it tomorrow

**Comment by stepandersen** [comment]
> Could a `hashchange` event listener suffice?

No, there isn't necessarily a # in the url, and it looks like `hashchange` only fires if you set `location.hash = "123"` in js.
