### ISSUE TITLE
Missing components from script export

### ISSUE THREAD

**Issue by johnhaavardstun** [SwedbankPay/design.swedbankpay.com#298]
The accordion and sidebar components are missing from the named exports of the entrypoint, leading to the globals `swedbankpay` and `dg` differing. Note that you can still access the components from via `swedbankpay.default.accordion|sidebar` if you need to.

As a side-question - are there any different use cases for each global (the documentation uses `dg`, so that's probably what we'll use, I just noticed this issue during our migration)?

**Comment by VikingTristan** [comment]
It's the `dg` global that should be used. The Accordion and Sidebar components will be patched into it asap.

Is your `swedbankpay` global filled with components or is it empty? To be honest, this brand global is kind of a mystery at the time of writing.

**Comment by VikingTristan** [comment]
This is what I get when checking the swedbankpay global
![image](https://user-images.githubusercontent.com/26485094/76540750-e17fda00-6482-11ea-9819-9f069f1af992.png)

**Comment by johnhaavardstun** [comment]
Mine's quite packed (version: https://design.swedbankpay.com/v/4.5.0/scripts/dg.js, import through script tag):
![image](https://user-images.githubusercontent.com/15321684/76609359-92d04f80-6517-11ea-8aed-04c5d7c83b93.png)

To be clear: accordion and sidebar *are* in `dg`, so if you (correctly) use that everything seems to be in order, so if the brand global is (pointless|deprecated|going away), then might not require action.
