### ISSUE TITLE
Topbar border question

### ISSUE THREAD

**Issue by VikingTristan** [SwedbankPay/design.swedbankpay.com#340]
There's a border top on the topbar-nav class that seems a bit off.

![image](https://user-images.githubusercontent.com/26485094/83862182-dfe04e00-a721-11ea-9e91-fc554cb0d3c6.png)

![image](https://user-images.githubusercontent.com/26485094/83862297-069e8480-a722-11ea-8372-5c141e7d02fa.png)

It's sort of hard to see, but it's there, I promise 🙏 .

**To Reproduce**
1. Go to 'https://design.swedbankpay.com/v/4.7.0/components/topbar'
2. Scroll down to 'Wide topbar'
3. See border on nav

**Possible fix**
Probably just remove this rule
![image](https://user-images.githubusercontent.com/26485094/83862861-cf7ca300-a722-11ea-8186-915d8ce2ca10.png)

**Comment by pthoang** [comment]
Yup, that should probably not be there. Not sure how that got there to be honest, but I guess it was my trying out some stuff and forgetting to remove it. Will fix!
