### ISSUE TITLE
Favicon in design guide v5

### ISSUE THREAD

**Issue by SveinungTorresdal** [SwedbankPay/design.swedbankpay.com#433]
**Is your feature request related to a problem? Please describe.**

I've been bashing my head on a rather silly problem - favicons. Specifically we had something that downscaled an older logotype, and it used a library that TeamCity threw a fit about - the npm package `sharp`. God knows why. In the end, I bypassed the problem by copying the generated image from my local build to the image folder, and set the favicon directly.

Part of the frustration arose from a lack of readymade favicons to simply drop into the project. This is given some additional relevance by the logo having changed slightly in times since.

In fact, even the design guide itself uses an outdated logo now. Here's a comparison between what we use in consumer portal - which is **definitely** using the old one - against the design guide one.

![image](https://user-images.githubusercontent.com/48713549/107217312-4aaefb00-6a0e-11eb-8969-fd84ea23567b.png)

**Describe the solution you'd like**

Under the logotype page we should have a **favicon** section with download links. 

**Describe alternatives you've considered**

I've considered personally downloading the logotype and modifying it. However, this can quickly cause fragmentation across products as everyone uses _slightly_ modified, or even unmodified versions of the logotype as a favicon. This seems counterproductive when the design guide could simply offer standardized logotypes for this usecase.

**Additional context**

_Old logo_
![favicon-96](https://user-images.githubusercontent.com/48713549/107217851-12f48300-6a0f-11eb-9561-d3bb6d291b0b.png) 

_New logo_
![image](https://user-images.githubusercontent.com/48713549/107217722-de80c700-6a0e-11eb-982e-257e5a2c43cf.png)

**Context**

Favicons are one of the most readily recognized aspects of websites. It appears on the tab in browsers, on bookmarks, etc. Therefore we should have a consistent standard for this to stay on brand. Additionally, having a detailed description of favicons will also help mitigate technical issues, such as what image size to host the icon at.

**Comment by VikingTristan** [comment]
Fixed in [this pull request](https://github.com/SwedbankPay/design.swedbankpay.com/pull/455) which is included in the next release.

**Comment by VikingTristan** [comment]
According to slack conversations, favicons will be available for download, but not in the current release.

**Comment by PhungNg** [comment]
This issue is fixed on [release/7.0.0](https://github.com/SwedbankPay/design.swedbankpay.com/releases/tag/7.0.0)
