### ISSUE TITLE
Tooltips cannot be used with keyboard

### ISSUE THREAD

**Issue by SveinungTorresdal** [SwedbankPay/design.swedbankpay.com#516]
The Design Guide offers [Tooltips](https://design.swedbankpay.com/v/6.0.1/components/tooltips). These are excellent for users employing the mouse. However, it has a critical flaw; it cannot be viewed using only the keyboard.

Here is the tooltip using the mouse.

![image](https://user-images.githubusercontent.com/48713549/127318670-59d85431-7031-4eaf-bacb-9c2e36c3f15f.png)

Here is an attempt to view the tooltip using the keyboard.

![image](https://user-images.githubusercontent.com/48713549/127318639-11158ad7-0d8b-4cbf-a3e0-3413a50fcb29.png)

**Describe the bug**

For the purposes of helping users with reduced capabilities we should strive to make the website(s) keyboard accessible. Towards that end things that can be done with a mouse should also be doable with a keyboard.

As it stands you cannot view a tooltip without using the mouse.

**To Reproduce**
1. Go to the design guide page for [Tooltips](https://design.swedbankpay.com/v/6.0.1/components/tooltips)
2. Verify that hovering over one of the tooltip buttons show the tooltip.
3. Click the button. It now has focus. You can verify it has focus by entering this into the developer console: `document.activeElement`.
4. Move away the cursor so the button does not have a hover effect.
5. The tooltip disappears, even though the element is both active and has the current focus of the keyboard. Using the `⭾ Tab` key, you can navigate back and forth between the buttons, but the tooltip will not appear.

**Expected behavior**

When an element with a tooltip has focus it should show the tooltip.

**Actual behavior**

No tooltip is shown.

**Possible fix**

This is a lazy fix that shouldn't be implemented wholesale, but this is what I've verified works:

```css
[data-tooltip]:focus-within .tooltip, [data-tooltip]:focus-within:after, [data-tooltip]:focus-within:before {
  opacity: 1 !important;
}
[data-tooltip]:focus-within .tooltip, [data-tooltip]:focus-within:after {
  content: attr(data-tooltip) !important;
}
```

**Screenshots**

Here is the tooltip using the mouse.

![image](https://user-images.githubusercontent.com/48713549/127318670-59d85431-7031-4eaf-bacb-9c2e36c3f15f.png)

Here is an attempt to view the tooltip using the keyboard.

![image](https://user-images.githubusercontent.com/48713549/127318639-11158ad7-0d8b-4cbf-a3e0-3413a50fcb29.png)

It should instead look like this.

![image](https://user-images.githubusercontent.com/48713549/127319379-bcdbaa23-63fa-49e0-b28b-6e4c24bf5ec6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

While not a bug, non-interactive elements that have a tooltip should be made interactive. The design guide should include this information.

For example:
It is doubly impossible to see the tooltip in this image without a mouse. Firstly, clicking the label diverts the user to the input. You also cannot place focus on the icon itself at all. In addition, the tooltip should probably be on the form group?

![image](https://user-images.githubusercontent.com/48713549/127319627-9a8b1a8b-14af-4d04-9d2b-c08ae3196881.png)

**Comment by eskilsen** [comment]
This should be solved in v/9.
