### ISSUE TITLE
Togglebox focus state outline

### ISSUE THREAD

**Issue by VikingTristan** [SwedbankPay/design.swedbankpay.com#558]
When using `label-top` extension class on togglebox, the focus state renders an unfortunate position on outline.

**Screenshots**
![image](https://user-images.githubusercontent.com/26485094/136023354-1781a092-790d-4565-be7d-27257d2034b5.png)

**Comment by eskilsen** [comment]
PR created now. Should work 💯

**Comment by VikingTristan** [comment]
Cool!
BTW issue will be closed automatically when referenced PR is merged :)
