### ISSUE TITLE
Additional options for component initialization

### ISSUE THREAD

**Issue by OAMPfed** [SwedbankPay/design.swedbankpay.com#657]
**Summary of the feature request**

In the TMS project we run UI tests for all pages and features, which can take 20 minutes (and growing). During our patching of some flaky tests we noticed that our test framework didn't play nice with timeouts and animations. We run unique CSS now if the project is in a test environment that disables animations, and we monkey patch in some code that hijacks the `setTimeout` and set it to 0ms so all sheets are instant. Disabling animations has cut the tests in half, so it would be preferable to have additional options during `component.init()` so we can disable everyting in the same place.

**Solution(?)**

Having the option to initialize like this would be preferable:

`dg.sheet.init({ options: { timeout: 0, animations: false } })`

**Current workaround:**

We are currently running optional CSS and JS code that overwrites both the animations and the timeout.

Why is this change important to you? How would you use it?
How can it benefit other users?

**Benefits:**

For UI tests this eliminates time spent waiting for tests to clear (or not), and makes for faster builds in the azure pipeline.

**Comment by johnhaavardstun** [comment]
An alternative way to look at it could be to tie it to `prefers-reduced-motion`?

**Comment by eskilsen** [comment]
Update. After reading about prefers-reduced-motion doc, I think we will implement this solution.
