### ISSUE TITLE
Sidebar v2 navigation improvements

### ISSUE THREAD

**Issue by trieutran91** [SwedbankPay/design.swedbankpay.com#733]
**Describe the bug**

The first level of the sidebar currently has an empty `<a>` tag. This should have a `href` in order to work in use cases without JavaScript. Also add `click` to `<a>` and `event.preventDefault()` to preserve the current behavior.

**Comment by eskilsen** [comment]
This is already implemented in previous versions. So try to update the DG version 💯 
Will close this issue.
